### ISSUE TITLE
Question: removing the fragment from the stack will clear the memory occupied by a fragment?

### ISSUE THREAD

**Issue by raviteja06** [rathodchintan/Fragment-Back-Stack#2]
Normally, when they remove a fragment from the manager I have seen people doing pop back stack, but here I don't see anything like add to back stack or pop back stack. Will it have any effect on memory consumption? Thanks in advance.

**Comment by ChintanRathod** [comment]
Yes. That will impact. In this example, fragments are managed in user created stack. So object of that fragment will persist in memory. This example is helpful if you need to manage tabs. I am using this approach in many of our business applications and I don't found any problem with this for memory. Memory issue will be there when you are using 10 to 20+ fragments in stack and you are not freeing memory.

**Comment by raviteja06** [comment]
Thanks. BTW, ur approach to back stack the fragments is very nice. I asked many people to look into this approach. 

Keep rocking dude.

---

Best Regards,

Ravi Gadipudi

On Mon, Jan 18, 2016 at 7:54 PM -0800, "Chintan Rathod" notifications@github.com wrote:

Yes. That will impact. In this example, fragments are managed in user created stack. So object of that fragment will persist in memory. This example is helpful if you need to manage tabs. I am using this approach in many of our business applications and I don't found any problem with this for memory.

**Comment by ChintanRathod** [comment]
Thank you very much for your words. :)
